// Zavrsni Vue/SmartTask/src/components/Home/TaskContainerToggle.vue
<template>
    <h1>Welcome Back, {{ props.username }}!</h1>
    <button v-show="!showing" @click="changeShowing" 
            id="showNewTask" class="boldano">
            New Task
    </button>
    <NewTaskContainer 
                      v-show="showing" 
                      :taskToUpdate="taskToUpdate" 
                      @refreshTasks="$emit('refreshTasks')"
                      @stopShowing="showing = !showing"
                      @startShowing="showing = true">
    </NewTaskContainer>
</template>

<script setup>
    import NewTaskContainer from './NewTaskContainer.vue'
    import { ref } from  "vue"
    const showing  = ref(false);
    const props = defineProps(['taskToUpdate', 'username'])
    defineEmits(['refreshTasks'])

    const changeShowing = () => {
        showing.value = !showing.value;
    }
</script>

// Zavrsni REACT/SmartTask/src/TaskContainerToggle.jsx
import NewTaskContainer from "./NewTaskContainer";
import { useState, useContext } from 'react'
import { TaskContext } from "./App";

function TaskContainerToggle(props) {
    const [showing, setShowing] = useState(false);
    const { user } = useContext(TaskContext);

    const changeShowContainer = () => {
        setShowing(s => !s)
    }

    return (
        <>
            <h1>Welcome back, { user.username }!</h1>

            <button id="showNewTask" className="boldano" onClick={changeShowContainer} 
            style={showing ? {display:'none'} : {display:'block'}}>
            New Task
            </button>
            
            <NewTaskContainer style={showing ? {display:'block'} : {display:'none'}}
                              showing={showing}
                              setShowing={setShowing}  ></NewTaskContainer>
        </>
    );
}

export default TaskContainerToggle;
