// Zavrsni Vue/SmartTask/src/components/Home/Task.vue
<template>
    <div class="task flex">
        <div id="title" class="flex">
            <input @click="$emit('changeCompletion', currentTask.id)" type="checkbox"
                   :checked="currentTask.completed" />
            <p :style="{color:chosenColor}" class="boldano flex">
                {{ currentTask.title }} ({{ currentTask.dueDate }})
            </p>
        </div>
        <div id="edit" class="flex">
            <button :style="{backgroundColor: chosenColor}" 
                    @click="$emit('updateTask', currentTask)">
                    Edit
            </button>
            <button :style="{backgroundColor: chosenColor}" 
                    @click="$emit('deleteTask', currentTask.id)">
                    Delete
            </button>
        </div>
    </div>
</template>

<script setup>
    import { computed, ref, watch } from 'vue'
    const props = defineProps(['task'])
    const emit = defineEmits(['changeCompletion', 'updateTask', 'deleteTask'])
    const currentTask = ref({
        id: props.task.id,
        title: props.task.title,
        dueDate: props.task.dueDate,
        priority: props.task.priority,
        completed: props.task.completed
    })
    const determineColor = (priority) => {
        switch (priority) {
            case 'Low':
                return '#9CA3AF';
            case 'Mid':
                return '#FACC15';
            case 'High':
                return '#EF4444';
        }
    }
    const chosenColor = computed(() => {
        return currentTask.value.completed ? '#10B981' : determineColor(currentTask.value.priority);
    })

    watch(() => props.task, (newVal) => {
        currentTask.value = { ...newVal }
    }, { deep: true, immediate: true })
</script>

// Zavrsni REACT/SmartTask/src/Task.jsx
import axios from 'axios';
import { useContext } from 'react'
import { TaskContext } from './App';

const determineColor = priority => {
        switch (priority) {
                case 'Low':
                    return '#9CA3AF';
                case 'Mid':
                    return '#FACC15';
                case 'High':
                    return '#EF4444';
                default:
                    alert('You have to select a priority value...');
                    return null;
            }
}

function Task(props) {
    const currentTask = props.task
    const { setEditingTask, fetchTasks } = useContext(TaskContext);
    const deleteTask = (e) => {
        axios.delete(`http://localhost:3000/api/tasks/${currentTask.id}`)
             .then(res => {
                fetchTasks();
             })
             .catch(err => console.error(err));
    }
    const startEditing = (e) => {
        setEditingTask(currentTask.id)
    }
    const changeCompletion = () => {
        axios.put(`http://localhost:3000/api/tasks/${currentTask.id}/toggle`)
            .then(res => {
                fetchTasks();
            })
            .catch(err => console.error(err));
    }
    const activeColor = currentTask.completed ? '#10B981' : determineColor(currentTask.priority);

    return (
        <div className="task flex">
            <div id="title" className="flex">
                <input type="checkbox" checked={currentTask.completed} onChange={changeCompletion} />
                <p className="boldano flex" 
                style={{color:activeColor}} >
                    {currentTask.title} ({currentTask.dueDate})
                </p>
            </div>
            <div id="edit" className="flex">
                <button onClick={startEditing} style={{backgroundColor:activeColor}} >Edit</button>
                <button onClick={deleteTask} style={{backgroundColor:activeColor} } >Delete</button>
            </div>
        </div>
    )

}

export default Task;
